01 add game tiles
tmdeim-git/hackathon-chainlink-game pull request #1
Opened 2024-05-04 22:36 UTC by RaulSima

2024-05-04 23:08 UTC, tmdeim-git requested changes

2024-05-04 23:08 UTC, tmdeim-git commented on front-end/src/game/GameScreen.tsx
>      }
mouseWheel = (e) => {
    let { zoom, offsetX, offsetY } = this.state;
  
    const rect = e.target.getBoundingClientRect();
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;
  
    const zoomFactor = 1.1;
  
    let newZoom;
    if (e.deltaY < 0) {
      newZoom = zoom * zoomFactor;
    } else {
      newZoom = zoom / zoomFactor;
    }
  
    newZoom = Math.min(Math.max(newZoom, 1), 2);
  
    const zoomChange = newZoom / zoom;
  
    offsetX = mouseX - zoomChange * (mouseX - offsetX);
    offsetY = mouseY - zoomChange * (mouseY - offsetY);
  
    this.setState({
      zoom: newZoom,
      offsetX: offsetX,
      offsetY: offsetY,
    });
  
    e.preventDefault();
  };

2024-05-04 23:08 UTC, tmdeim-git commented on front-end/src/game/GameScreen.tsx
>      }
This code is aware of the position of the mouse and zooms accordingly.

2024-05-05 00:59 UTC, TheVortex8 approved these changes

2024-05-05 23:15 UTC, merged